### ISSUE TITLE
Global route registrar

### ISSUE THREAD

**Issue by richardanaya** [kdy1/rweb#57]
I'm wondering if we can write some code to simplify this long list of `or`

```rust
#[tokio::main]
async fn main() {
    serve(output().or(product()).or(products()).or(search())).run(([127, 0, 0, 1], 3030)).await;
}
```

i'm wondering if we can use `lazy_static` to have some sort of global registrar of routes that's called using the `rweb` macros `get`,`post`, etc.  And we could possibly simplify server startup to:

```
#[tokio::main]
async fn main() {
    rweb::run_server(([127, 0, 0, 1], 3030)).await;
}
```

We'd have a version for HTTP 2 as well

Does that sound like an idea you'd like?

**Comment by richardanaya** [comment]
I ran into difficulties when I tried to unify routes:

```rust
use ctor::*;
use lazy_static::*;
use rweb::*;
use std::sync::Mutex;

// This global would live in rweb
lazy_static! {
    static ref FILTER_LIST: Mutex<Vec<rweb::filters::BoxedFilter<(Box<dyn warp::Reply>,)>>> =
        Mutex::new(vec![]);
}

#[get("/foo")]
fn foo() -> Box<dyn warp::Reply> {
    Box::new(String::from(
        "content type will be 'text/plain' as you return String",
    ))
}

// this is a new function that would be injected by #[get("/foo")]
#[ctor]
fn foo_global() {
    FILTER_LIST.lock().unwrap().push(foo().boxed());
}

#[get("/bar")]
fn bar() -> Box<dyn warp::Reply> {
    Box::new(String::from(
        "content type will be 'text/plain' as you return String",
    ))
}

// this is a new function that would be injected by #[get("/bar")]
#[ctor]
fn bar_global() {
    FILTER_LIST.lock().unwrap().push(bar().boxed());
}

// This is a new function that would be added rweb
async fn run_server(addr: impl Into<std::net::SocketAddr>) {
    let mut all_filters = FILTER_LIST.lock().unwrap();
    println!("{}", all_filters.len());
    if all_filters.len() > 0 {
        let a = all_filters.pop().unwrap();
        let mut combined_filter = a;
        loop {
            if all_filters.len() == 0 {
                break;
            }
            let a = all_filters.pop().unwrap();
            combined_filter = combined_filter.or(a).unify().boxed();
        }
        let (spec, filter) = openapi::spec().build(move || combined_filter);
        serve(filter.or(openapi_docs(spec))).run(addr).await;
    }
}

#[tokio::main]
async fn main() {
    run_server(([127, 0, 0, 1], 3030)).await
}
```

**Comment by SafariMonkey** [comment]
Just commenting here to say that I have just been looking over this crate, and the fact that route registration was explicit was a plus in my book. In my opinion, the per-handler overhead of writing the registration manually is minor. `rweb` looks like it hits the sweet spot for me between clear route definitions and not obfuscating what's happening. It would also be preferable to me that it's always possible to drop down from the macro level where necessary - I don't know if `rweb` supports this, but as it appears to just be creating warp filters, I would assume that converting an endpoint to a standard warp filter is currently doable (and supported) if necessary.

Implicit global route merging would also prevent access to create optimisations like https://github.com/seanmonstar/warp/issues/619#issuecomment-660719917, where I created a macro to minimise the nesting depth of routes in order to improve compile time.

**Comment by richardanaya** [comment]
Great points. Maybe this isn't an issue after all! :) I'll close this for now
